<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Async Await</title>
  <link rel="stylesheet" href="../base.css">
</head>

<body>
  <script>
    function wait(ms = 0) {
      return new Promise((resolve) => {
        setTimeout(resolve, ms);
      });
    }

    function makePizza(toppings = []) {
      return new Promise(function (resolve, reject) {
        // reject if people try with pineapple
        if (toppings.includes('pineapple')) {
          reject('Seriously? Get out üçç');
        }
        const amountOfTimeToBake = 500 + toppings.length * 200;
        // wait 1 second for the pizza to cook:
        setTimeout(function () {
          // when you are ready, you can resolve this promise
          resolve(`Here is your pizza üçï with the toppings ${toppings.join(' ')}`);
        }, amountOfTimeToBake);
        // if something went wrong, we can reject this promise;
      });
    }

    // Four ways to handle errors

    // Try and Catch
    // async function go() {
    //   try {
    //     const pizza = await makePizza(['pineapple']);
    //     console.log(pizza);
    //   } catch (err) {
    //     console.log('Oh noooooo');
    //     console.log(err);
    //   }
    // }

    function handleError(err) {
      console.log('Ohhhh nooooo');
      console.log(err);
    }

    async function go() {
      const pizza = await makePizza(['pineapple']);
      console.log(pizza);
      return pizza;
    }

    // Or handle error when you call function
    // go().catch(handleError);

    // when you mark a function as async it will immediately return a promise

    // HOF - Higher order function - function that returns another function
    // this way you don't have to worry about error handling in the function just write them normally

    // catch it at runtime
    // go().catch(handleError); // best option

    // make a safe function with a HOF
    function makeSafe(fn, errorHandler) {
      return function () {
        fn().catch(errorHandler);
      };
    }

    // go(); // unsafe

    const safeGo = makeSafe(go, handleError); // good for node land
    safeGo();
  </script>
</body>

</html>